import { EMPTY_CARD, type CardDraft } from "./model";

export type CardPreset = {
  id: string;
  name: string;
  set: "FOUNDATION" | "PLANT 1★" | "STONE 1★" | "PLANT 2★" | "STONE 2★" | "PLANT 3★" | "STONE 3★" | "PLANT 4★" | "STONE 4★";
  system: CardDraft["faction"];
  type: "ACTION" | "MAGIC" | "PASSIVE";
  draftType: CardDraft["type"];
  stars: number;
  energy: number;
  mass: number;
  outcomeKind: CardDraft["outcome_kind"];
  base: number;
  coefficient: number;
  target: string;
  rules: string;
  icons: string[];
  art: string;
  effects: string;
  retentionPolicy?: CardDraft["retention_policy"];
  occupiesDrawSlot?: boolean;
};

const icon = (name: string) => `/assets/cards/icons/${name}_v01.png`;
const plantArt = (id: string) => `/assets/cards/sets/plant_one_star/${id}_art_v03.png`;
const stoneArt = (id: string) => `/assets/cards/sets/stone_one_star/${id}_art_v03.png`;
const plantTwoStarArt = (id: string) => `/assets/cards/sets/plant_two_star/${id}_art_v01.png`;
const stoneTwoStarArt = (id: string) => `/assets/cards/sets/stone_two_star/${id}_art_v01.png`;
const libraryArt = (system: "plant" | "stone", tier: "advanced" | "rare", id: string) => `/assets/cards/art_library/${system}/${tier}/${id}_v01.png`;

export const CARD_PRESETS: CardPreset[] = [
  { id: "stone_basalt_breaker", name: "BASALT BREAKER", set: "FOUNDATION", system: "STONE", type: "ACTION", draftType: "ATTACK", stars: 3, energy: 2, mass: 2, outcomeKind: "DAMAGE", base: 12, coefficient: 4, target: "SINGLE_ENEMY", rules: "Deal 12 damage. Apply 2 Fracture.", icons: [icon("system_stone"), icon("type_action")], art: "/assets/cards/starter/basalt_breaker_art_v01.png", effects: '[{"type":"DAMAGE","base":12,"compatible_system":"STONE","amplification_coefficient":4},{"type":"APPLY_STATUS","status_id":"fracture","stacks":2}]' },
  { id: "plant_verdant_ritual", name: "VERDANT RITUAL", set: "FOUNDATION", system: "PLANT", type: "MAGIC", draftType: "TACTIC", stars: 4, energy: 2, mass: 1, outcomeKind: "POISON", base: 4, coefficient: 5, target: "SINGLE_ENEMY", rules: "Apply 4 Poison. Grow 1 Seed.", icons: [icon("system_plant"), icon("type_magic")], art: "/assets/cards/starter/verdant_ritual_art_v01.png", effects: '[{"type":"APPLY_STATUS","status_id":"poison","stacks":4,"compatible_system":"PLANT","amplification_coefficient":5},{"type":"SUMMON","summon_id":"plant_seed"}]' },
  { id: "hybrid_crystal_heart", name: "CRYSTAL HEART", set: "FOUNDATION", system: "HYBRID", type: "PASSIVE", draftType: "PASSIVE", stars: 5, energy: 0, mass: 3, outcomeKind: "ENERGY", base: 1, coefficient: 6, target: "SELF", rules: "First Shield each turn grants +1 Energy.", icons: [icon("system_hybrid"), icon("type_passive")], art: "/assets/cards/starter/crystal_heart_art_v01.png", effects: '[{"type":"TRIGGER","event":"FIRST_SHIELD_GAINED","effect":{"type":"GAIN_ENERGY","base":1,"compatible_system":"HYBRID","amplification_coefficient":6}}]', retentionPolicy: "RETAIN_IN_HAND", occupiesDrawSlot: true },

  { id: "plant_thorn_snap", name: "THORN SNAP", set: "PLANT 1★", system: "PLANT", type: "ACTION", draftType: "ACTION", stars: 1, energy: 1, mass: 1, outcomeKind: "DAMAGE", base: 3, coefficient: 4, target: "SINGLE_ENEMY", rules: "Deal 3 damage.", icons: [icon("system_plant"), icon("type_action")], art: plantArt("plant_thorn_snap"), effects: '[{"type":"DAMAGE","base":3,"compatible_system":"PLANT","amplification_coefficient":4,"rounding":"FLOOR"}]' },
  { id: "plant_sap_leech", name: "SAP LEECH", set: "PLANT 1★", system: "PLANT", type: "ACTION", draftType: "ACTION", stars: 1, energy: 1, mass: 1, outcomeKind: "DAMAGE", base: 2, coefficient: 4, target: "SINGLE_ENEMY", rules: "Deal 2 damage. Heal Hull for 50% of damage dealt.", icons: [icon("system_plant"), icon("type_action")], art: plantArt("plant_sap_leech"), effects: '[{"type":"DAMAGE","base":2,"compatible_system":"PLANT","amplification_coefficient":4,"rounding":"FLOOR","result_key":"damage_dealt"},{"type":"HEAL_HULL","value_source":{"type":"EFFECT_RESULT","effect_key":"damage_dealt","ratio":0.5},"rounding":"FLOOR"}]' },
  { id: "plant_bloom_mend", name: "BLOOM MEND", set: "PLANT 1★", system: "PLANT", type: "ACTION", draftType: "ACTION", stars: 1, energy: 1, mass: 1, outcomeKind: "HEAL_HULL", base: 3, coefficient: 6, target: "SELF", rules: "Heal 3 Hull.", icons: [icon("system_plant"), icon("type_action")], art: plantArt("plant_bloom_mend"), effects: '[{"type":"HEAL_HULL","base":3,"compatible_system":"PLANT","amplification_coefficient":6,"rounding":"FLOOR"}]' },
  { id: "plant_barkskin", name: "BARKSKIN", set: "PLANT 1★", system: "PLANT", type: "MAGIC", draftType: "BUFF", stars: 1, energy: 1, mass: 1, outcomeKind: "GAIN_DEFEND", base: 2, coefficient: 0, target: "SELF", rules: "Gain +2 Defend for 3 turns.", icons: [icon("system_plant"), icon("type_magic")], art: plantArt("plant_barkskin"), effects: '[{"type":"BUFF_STAT","stat":"DEFEND","base":2,"duration_turns":3,"compatible_system":"PLANT","amplification_coefficient":0,"rounding":"FLOOR"}]' },
  { id: "plant_regrowth_cycle", name: "REGROWTH CYCLE", set: "PLANT 1★", system: "PLANT", type: "MAGIC", draftType: "BUFF", stars: 1, energy: 2, mass: 1, outcomeKind: "HEAL_HULL", base: 2, coefficient: 5, target: "SELF", rules: "At turn start, heal 2 Hull for 3 turns.", icons: [icon("system_plant"), icon("type_magic")], art: plantArt("plant_regrowth_cycle"), effects: '[{"type":"APPLY_STATUS","status_id":"regrowth","tick_effect":{"type":"HEAL_HULL","base":2,"compatible_system":"PLANT","amplification_coefficient":5,"rounding":"FLOOR"},"duration_turns":3,"duration_amplification_coefficient":3}]' },
  { id: "plant_solar_bloom", name: "SOLAR BLOOM", set: "PLANT 1★", system: "PLANT", type: "MAGIC", draftType: "BUFF", stars: 1, energy: 1, mass: 1, outcomeKind: "ENERGY", base: 1, coefficient: 3, target: "SELF", rules: "Gain +1 extra Energy at turn start for 2 turns.", icons: [icon("system_plant"), icon("type_magic")], art: plantArt("plant_solar_bloom"), effects: '[{"type":"APPLY_STATUS","status_id":"solar_bloom","tick_effect":{"type":"GAIN_ENERGY","base":1,"compatible_system":"PLANT","amplification_coefficient":3,"rounding":"FLOOR"},"duration_turns":2}]' },
  { id: "plant_guardian_seed", name: "GUARDIAN SEED", set: "PLANT 1★", system: "PLANT", type: "PASSIVE", draftType: "PASSIVE", stars: 1, energy: 0, mass: 1, outcomeKind: "GAIN_DEFEND", base: 1, coefficient: 10, target: "SELF", rules: "While retained in hand, gain +1 Defend. You may discard this card.", icons: [icon("system_plant"), icon("type_passive")], art: plantArt("plant_guardian_seed"), effects: '[{"type":"AURA","condition":{"card_in_hand":true},"stat":"DEFEND","base":1,"compatible_system":"PLANT","amplification_coefficient":10,"rounding":"FLOOR"}]', retentionPolicy: "RETAIN_IN_HAND", occupiesDrawSlot: true },

  { id: "stone_meteor_fang", name: "METEOR FANG", set: "STONE 1★", system: "STONE", type: "ACTION", draftType: "ACTION", stars: 1, energy: 1, mass: 1, outcomeKind: "DAMAGE", base: 5, coefficient: 3, target: "SINGLE_ENEMY", rules: "Deal 5 damage.", icons: [icon("system_stone"), icon("type_action")], art: stoneArt("stone_meteor_fang"), effects: '[{"type":"DAMAGE","base":5,"compatible_system":"STONE","amplification_coefficient":3,"rounding":"FLOOR"}]' },
  { id: "stone_crushing_aegis", name: "CRUSHING AEGIS", set: "STONE 1★", system: "STONE", type: "ACTION", draftType: "ACTION", stars: 1, energy: 1, mass: 1, outcomeKind: "DAMAGE", base: 4, coefficient: 3, target: "SINGLE_ENEMY", rules: "Deal 4 damage. Gain Defend equal to 50% of damage dealt.", icons: [icon("system_stone"), icon("type_action")], art: stoneArt("stone_crushing_aegis"), effects: '[{"type":"DAMAGE","base":4,"compatible_system":"STONE","amplification_coefficient":3,"rounding":"FLOOR","result_key":"damage_dealt"},{"type":"GAIN_DEFEND","value_source":{"type":"EFFECT_RESULT","effect_key":"damage_dealt","ratio":0.5},"rounding":"FLOOR"}]' },
  { id: "stone_basalt_bulwark", name: "BASALT BULWARK", set: "STONE 1★", system: "STONE", type: "ACTION", draftType: "ACTION", stars: 1, energy: 1, mass: 1, outcomeKind: "GAIN_DEFEND", base: 5, coefficient: 4, target: "SELF", rules: "Gain 5 Defend.", icons: [icon("system_stone"), icon("type_action")], art: stoneArt("stone_basalt_bulwark"), effects: '[{"type":"GAIN_DEFEND","base":5,"compatible_system":"STONE","amplification_coefficient":4,"rounding":"FLOOR"}]' },
  { id: "stone_orbiting_plate", name: "ORBITING PLATES", set: "STONE 1★", system: "STONE", type: "MAGIC", draftType: "BUFF", stars: 1, energy: 1, mass: 1, outcomeKind: "GAIN_DEFEND", base: 4, coefficient: 0, target: "SELF", rules: "Gain +4 Defend for 3 turns.", icons: [icon("system_stone"), icon("type_magic")], art: stoneArt("stone_orbiting_plate"), effects: '[{"type":"BUFF_STAT","stat":"DEFEND","base":4,"duration_turns":3,"compatible_system":"STONE","amplification_coefficient":0,"rounding":"FLOOR"}]' },
  { id: "stone_crystal_reinforce", name: "CRYSTAL REINFORCE", set: "STONE 1★", system: "STONE", type: "MAGIC", draftType: "BUFF", stars: 1, energy: 2, mass: 1, outcomeKind: "GAIN_DEFEND", base: 3, coefficient: 3, target: "SELF", rules: "At turn start, gain 3 Defend for 3 turns.", icons: [icon("system_stone"), icon("type_magic")], art: stoneArt("stone_crystal_reinforce"), effects: '[{"type":"APPLY_STATUS","status_id":"crystal_reinforce","tick_effect":{"type":"GAIN_DEFEND","base":3,"compatible_system":"STONE","amplification_coefficient":3,"rounding":"FLOOR"},"duration_turns":3}]' },
  { id: "stone_geothermal_core", name: "GEOTHERMAL CORE", set: "STONE 1★", system: "STONE", type: "MAGIC", draftType: "BUFF", stars: 1, energy: 1, mass: 1, outcomeKind: "ENERGY", base: 1, coefficient: 2, target: "SELF", rules: "Gain +1 extra Energy at turn start for 2 turns.", icons: [icon("system_stone"), icon("type_magic")], art: stoneArt("stone_geothermal_core"), effects: '[{"type":"APPLY_STATUS","status_id":"geothermal_core","tick_effect":{"type":"GAIN_ENERGY","base":1,"compatible_system":"STONE","amplification_coefficient":2,"rounding":"FLOOR"},"duration_turns":2}]' },
  { id: "stone_sentinel", name: "STONE SENTINEL", set: "STONE 1★", system: "STONE", type: "PASSIVE", draftType: "PASSIVE", stars: 1, energy: 0, mass: 1, outcomeKind: "GAIN_DEFEND", base: 2, coefficient: 6, target: "SELF", rules: "While retained in hand, gain +2 Defend. You may discard this card.", icons: [icon("system_stone"), icon("type_passive")], art: stoneArt("stone_sentinel"), effects: '[{"type":"AURA","condition":{"card_in_hand":true},"stat":"DEFEND","base":2,"compatible_system":"STONE","amplification_coefficient":6,"rounding":"FLOOR"}]', retentionPolicy: "RETAIN_IN_HAND", occupiesDrawSlot: true },

  { id: "plant_thorn_volley", name: "THORN VOLLEY", set: "PLANT 2★", system: "PLANT", type: "ACTION", draftType: "ACTION", stars: 2, energy: 2, mass: 1, outcomeKind: "DAMAGE", base: 4, coefficient: 5, target: "ALL_ENEMIES", rules: "Deal 4 damage to all enemies.", icons: [icon("system_plant"), icon("type_action")], art: plantTwoStarArt("plant_thorn_volley"), effects: '[{"type":"DAMAGE","base":4,"target":"ALL_ENEMIES","compatible_system":"PLANT","amplification_coefficient":5,"rounding":"FLOOR"}]' },
  { id: "plant_siphon_bloom", name: "SIPHON BLOOM", set: "PLANT 2★", system: "PLANT", type: "ACTION", draftType: "ACTION", stars: 2, energy: 2, mass: 1, outcomeKind: "DAMAGE", base: 4, coefficient: 5, target: "SINGLE_ENEMY", rules: "Deal 4 damage. Heal Hull for 75% of damage dealt.", icons: [icon("system_plant"), icon("type_action")], art: plantTwoStarArt("plant_siphon_bloom"), effects: '[{"type":"DAMAGE","base":4,"compatible_system":"PLANT","amplification_coefficient":5,"rounding":"FLOOR","result_key":"damage_dealt"},{"type":"HEAL_HULL","value_source":{"type":"EFFECT_RESULT","effect_key":"damage_dealt","ratio":0.75},"rounding":"FLOOR"}]' },
  { id: "plant_spore_cleanse", name: "SPORE CLEANSE", set: "PLANT 2★", system: "PLANT", type: "ACTION", draftType: "ACTION", stars: 2, energy: 2, mass: 1, outcomeKind: "HEAL_HULL", base: 5, coefficient: 7, target: "SELF", rules: "Heal 5 Hull. Remove 1 negative status.", icons: [icon("system_plant"), icon("type_action")], art: plantTwoStarArt("plant_spore_cleanse"), effects: '[{"type":"HEAL_HULL","base":5,"compatible_system":"PLANT","amplification_coefficient":7,"rounding":"FLOOR"},{"type":"CLEANSE","count":1,"polarity":"NEGATIVE"}]' },
  { id: "plant_canopy_ward", name: "CANOPY WARD", set: "PLANT 2★", system: "PLANT", type: "MAGIC", draftType: "BUFF", stars: 2, energy: 2, mass: 1, outcomeKind: "GAIN_DEFEND", base: 3, coefficient: 3, target: "SELF", rules: "Gain +3 Defend for 4 turns.", icons: [icon("system_plant"), icon("type_magic")], art: plantTwoStarArt("plant_canopy_ward"), effects: '[{"type":"BUFF_STAT","stat":"DEFEND","base":3,"duration_turns":4,"compatible_system":"PLANT","amplification_coefficient":3,"rounding":"FLOOR"}]' },
  { id: "plant_germination_loop", name: "GERMINATION LOOP", set: "PLANT 2★", system: "PLANT", type: "MAGIC", draftType: "BUFF", stars: 2, energy: 2, mass: 1, outcomeKind: "HEAL_HULL", base: 3, coefficient: 6, target: "SELF", rules: "At turn start, heal 3 Hull for 4 turns.", icons: [icon("system_plant"), icon("type_magic")], art: plantTwoStarArt("plant_germination_loop"), effects: '[{"type":"APPLY_STATUS","status_id":"germination_loop","tick_effect":{"type":"HEAL_HULL","base":3,"compatible_system":"PLANT","amplification_coefficient":6,"rounding":"FLOOR"},"duration_turns":4,"duration_amplification_coefficient":4}]' },
  { id: "plant_photosynthetic_surge", name: "PHOTOSYNTHETIC SURGE", set: "PLANT 2★", system: "PLANT", type: "MAGIC", draftType: "BUFF", stars: 2, energy: 2, mass: 1, outcomeKind: "ENERGY", base: 1, coefficient: 4, target: "SELF", rules: "Gain +1 extra Energy at turn start for 3 turns.", icons: [icon("system_plant"), icon("type_magic")], art: plantTwoStarArt("plant_photosynthetic_surge"), effects: '[{"type":"APPLY_STATUS","status_id":"photosynthetic_surge","tick_effect":{"type":"GAIN_ENERGY","base":1,"compatible_system":"PLANT","amplification_coefficient":4,"rounding":"FLOOR"},"duration_turns":3}]' },
  { id: "plant_symbiotic_guard", name: "SYMBIOTIC GUARD", set: "PLANT 2★", system: "PLANT", type: "PASSIVE", draftType: "PASSIVE", stars: 2, energy: 0, mass: 1, outcomeKind: "GAIN_DEFEND", base: 2, coefficient: 8, target: "SELF", rules: "While retained, the first Hull heal each turn grants 2 Defend. You may discard this card.", icons: [icon("system_plant"), icon("type_passive")], art: plantTwoStarArt("plant_symbiotic_guard"), effects: '[{"type":"TRIGGER","condition":{"card_in_hand":true},"event":"FIRST_HULL_HEAL_EACH_TURN","effect":{"type":"GAIN_DEFEND","base":2,"compatible_system":"PLANT","amplification_coefficient":8,"rounding":"FLOOR"}}]', retentionPolicy: "RETAIN_IN_HAND", occupiesDrawSlot: true },

  { id: "stone_asteroid_barrage", name: "ASTEROID BARRAGE", set: "STONE 2★", system: "STONE", type: "ACTION", draftType: "ACTION", stars: 2, energy: 2, mass: 2, outcomeKind: "DAMAGE", base: 9, coefficient: 3, target: "SINGLE_ENEMY", rules: "Deal 3 damage three times.", icons: [icon("system_stone"), icon("type_action")], art: stoneTwoStarArt("stone_asteroid_barrage"), effects: '[{"type":"DAMAGE_REPEAT","base":3,"hits":3,"compatible_system":"STONE","amplification_coefficient":3,"rounding":"FLOOR"}]' },
  { id: "stone_seismic_rebound", name: "SEISMIC REBOUND", set: "STONE 2★", system: "STONE", type: "ACTION", draftType: "ACTION", stars: 2, energy: 2, mass: 2, outcomeKind: "DAMAGE", base: 6, coefficient: 3, target: "SINGLE_ENEMY", rules: "Deal 6 damage. Gain Defend equal to 75% of damage dealt.", icons: [icon("system_stone"), icon("type_action")], art: stoneTwoStarArt("stone_seismic_rebound"), effects: '[{"type":"DAMAGE","base":6,"compatible_system":"STONE","amplification_coefficient":3,"rounding":"FLOOR","result_key":"damage_dealt"},{"type":"GAIN_DEFEND","value_source":{"type":"EFFECT_RESULT","effect_key":"damage_dealt","ratio":0.75},"rounding":"FLOOR"}]' },
  { id: "stone_faultline_crush", name: "FAULTLINE CRUSH", set: "STONE 2★", system: "STONE", type: "ACTION", draftType: "ACTION", stars: 2, energy: 2, mass: 2, outcomeKind: "DAMAGE", base: 7, coefficient: 2, target: "SINGLE_ENEMY", rules: "Deal 7 damage. Apply 1 Fracture.", icons: [icon("system_stone"), icon("type_action")], art: stoneTwoStarArt("stone_faultline_crush"), effects: '[{"type":"DAMAGE","base":7,"compatible_system":"STONE","amplification_coefficient":2,"rounding":"FLOOR"},{"type":"APPLY_STATUS","status_id":"fracture","stacks":1}]' },
  { id: "stone_fortress_mantle", name: "FORTRESS MANTLE", set: "STONE 2★", system: "STONE", type: "MAGIC", draftType: "BUFF", stars: 2, energy: 2, mass: 2, outcomeKind: "GAIN_DEFEND", base: 6, coefficient: 1, target: "SELF", rules: "Gain +6 Defend for 3 turns.", icons: [icon("system_stone"), icon("type_magic")], art: stoneTwoStarArt("stone_fortress_mantle"), effects: '[{"type":"BUFF_STAT","stat":"DEFEND","base":6,"duration_turns":3,"compatible_system":"STONE","amplification_coefficient":1,"rounding":"FLOOR"}]' },
  { id: "stone_tectonic_bastion", name: "TECTONIC BASTION", set: "STONE 2★", system: "STONE", type: "MAGIC", draftType: "BUFF", stars: 2, energy: 2, mass: 2, outcomeKind: "GAIN_DEFEND", base: 5, coefficient: 2, target: "SELF", rules: "At turn start, gain 5 Defend for 3 turns.", icons: [icon("system_stone"), icon("type_magic")], art: stoneTwoStarArt("stone_tectonic_bastion"), effects: '[{"type":"APPLY_STATUS","status_id":"tectonic_bastion","tick_effect":{"type":"GAIN_DEFEND","base":5,"compatible_system":"STONE","amplification_coefficient":2,"rounding":"FLOOR"},"duration_turns":3}]' },
  { id: "stone_core_compression", name: "CORE COMPRESSION", set: "STONE 2★", system: "STONE", type: "MAGIC", draftType: "BUFF", stars: 2, energy: 2, mass: 2, outcomeKind: "ENERGY", base: 2, coefficient: 2, target: "SELF", rules: "Gain 3 Defend. At next turn start, gain 2 Energy.", icons: [icon("system_stone"), icon("type_magic")], art: stoneTwoStarArt("stone_core_compression"), effects: '[{"type":"GAIN_DEFEND","base":3,"compatible_system":"STONE","amplification_coefficient":2,"rounding":"FLOOR"},{"type":"DELAYED_EFFECT","delay_turns":1,"effect":{"type":"GAIN_ENERGY","base":2,"compatible_system":"STONE","amplification_coefficient":2,"rounding":"FLOOR"}}]' },
  { id: "stone_aegis_monolith", name: "AEGIS MONOLITH", set: "STONE 2★", system: "STONE", type: "PASSIVE", draftType: "PASSIVE", stars: 2, energy: 0, mass: 2, outcomeKind: "GAIN_DEFEND", base: 3, coefficient: 7, target: "SELF", rules: "While retained in hand, gain +3 Defend. You may discard this card.", icons: [icon("system_stone"), icon("type_passive")], art: stoneTwoStarArt("stone_aegis_monolith"), effects: '[{"type":"AURA","condition":{"card_in_hand":true},"stat":"DEFEND","base":3,"compatible_system":"STONE","amplification_coefficient":7,"rounding":"FLOOR"}]', retentionPolicy: "RETAIN_IN_HAND", occupiesDrawSlot: true },

  { id: "plant_briar_cascade", name: "BRIAR CASCADE", set: "PLANT 3★", system: "PLANT", type: "ACTION", draftType: "ACTION", stars: 3, energy: 2, mass: 2, outcomeKind: "DAMAGE", base: 6, coefficient: 6, target: "ALL_ENEMIES", rules: "Deal 6 damage to all enemies.", icons: [icon("system_plant"), icon("type_action")], art: libraryArt("plant", "advanced", "plant_briar_cascade"), effects: '[{"type":"DAMAGE","base":6,"target":"ALL_ENEMIES","compatible_system":"PLANT","amplification_coefficient":6,"rounding":"FLOOR"}]' },
  { id: "plant_crimson_graft", name: "CRIMSON GRAFT", set: "PLANT 3★", system: "PLANT", type: "ACTION", draftType: "ACTION", stars: 3, energy: 2, mass: 2, outcomeKind: "DAMAGE", base: 7, coefficient: 6, target: "SINGLE_ENEMY", rules: "Deal 7 damage. Heal Hull for 100% of damage dealt.", icons: [icon("system_plant"), icon("type_action")], art: libraryArt("plant", "advanced", "plant_crimson_graft"), effects: '[{"type":"DAMAGE","base":7,"compatible_system":"PLANT","amplification_coefficient":6,"rounding":"FLOOR","result_key":"damage_dealt"},{"type":"HEAL_HULL","value_source":{"type":"EFFECT_RESULT","effect_key":"damage_dealt","ratio":1},"rounding":"FLOOR"}]' },
  { id: "plant_purifying_mycelium", name: "PURIFYING MYCELIUM", set: "PLANT 3★", system: "PLANT", type: "ACTION", draftType: "ACTION", stars: 3, energy: 2, mass: 2, outcomeKind: "HEAL_HULL", base: 8, coefficient: 8, target: "SELF", rules: "Heal 8 Hull. Remove up to 2 negative statuses.", icons: [icon("system_plant"), icon("type_action")], art: libraryArt("plant", "advanced", "plant_purifying_mycelium"), effects: '[{"type":"HEAL_HULL","base":8,"compatible_system":"PLANT","amplification_coefficient":8,"rounding":"FLOOR"},{"type":"CLEANSE","count":2,"polarity":"NEGATIVE"}]' },
  { id: "plant_canopy_citadel", name: "CANOPY CITADEL", set: "PLANT 3★", system: "PLANT", type: "MAGIC", draftType: "BUFF", stars: 3, energy: 2, mass: 2, outcomeKind: "GAIN_DEFEND", base: 5, coefficient: 4, target: "SELF", rules: "Gain +5 Defend for 4 turns.", icons: [icon("system_plant"), icon("type_magic")], art: libraryArt("plant", "advanced", "plant_canopy_citadel"), effects: '[{"type":"BUFF_STAT","stat":"DEFEND","base":5,"duration_turns":4,"compatible_system":"PLANT","amplification_coefficient":4,"rounding":"FLOOR"}]' },
  { id: "plant_perpetual_spring", name: "PERPETUAL SPRING", set: "PLANT 3★", system: "PLANT", type: "MAGIC", draftType: "BUFF", stars: 3, energy: 3, mass: 2, outcomeKind: "HEAL_HULL", base: 5, coefficient: 7, target: "SELF", rules: "At turn start, heal 5 Hull for 4 turns.", icons: [icon("system_plant"), icon("type_magic")], art: libraryArt("plant", "advanced", "plant_perpetual_spring"), effects: '[{"type":"APPLY_STATUS","status_id":"perpetual_spring","tick_effect":{"type":"HEAL_HULL","base":5,"compatible_system":"PLANT","amplification_coefficient":7,"rounding":"FLOOR"},"duration_turns":4}]' },
  { id: "plant_heliotropic_engine", name: "HELIOTROPIC ENGINE", set: "PLANT 3★", system: "PLANT", type: "MAGIC", draftType: "BUFF", stars: 3, energy: 3, mass: 2, outcomeKind: "ENERGY", base: 2, coefficient: 5, target: "SELF", rules: "Gain +2 extra Energy at turn start for 2 turns.", icons: [icon("system_plant"), icon("type_magic")], art: libraryArt("plant", "advanced", "plant_heliotropic_engine"), effects: '[{"type":"APPLY_STATUS","status_id":"heliotropic_engine","tick_effect":{"type":"GAIN_ENERGY","base":2,"compatible_system":"PLANT","amplification_coefficient":5,"rounding":"FLOOR"},"duration_turns":2}]' },
  { id: "plant_symbiotic_lattice", name: "SYMBIOTIC LATTICE", set: "PLANT 3★", system: "PLANT", type: "PASSIVE", draftType: "PASSIVE", stars: 3, energy: 0, mass: 2, outcomeKind: "GAIN_DEFEND", base: 4, coefficient: 10, target: "SELF", rules: "While retained, the first Hull heal each turn grants 4 Defend.", icons: [icon("system_plant"), icon("type_passive")], art: libraryArt("plant", "advanced", "plant_symbiotic_lattice"), effects: '[{"type":"TRIGGER","condition":{"card_in_hand":true},"event":"FIRST_HULL_HEAL_EACH_TURN","effect":{"type":"GAIN_DEFEND","base":4,"compatible_system":"PLANT","amplification_coefficient":10,"rounding":"FLOOR"}}]', retentionPolicy: "RETAIN_IN_HAND", occupiesDrawSlot: true },

  { id: "stone_comet_hammer", name: "COMET HAMMER", set: "STONE 3★", system: "STONE", type: "ACTION", draftType: "ACTION", stars: 3, energy: 2, mass: 2, outcomeKind: "DAMAGE", base: 11, coefficient: 4, target: "SINGLE_ENEMY", rules: "Deal 11 damage.", icons: [icon("system_stone"), icon("type_action")], art: libraryArt("stone", "advanced", "stone_comet_hammer"), effects: '[{"type":"DAMAGE","base":11,"compatible_system":"STONE","amplification_coefficient":4,"rounding":"FLOOR"}]' },
  { id: "stone_fault_barrage", name: "FAULT BARRAGE", set: "STONE 3★", system: "STONE", type: "ACTION", draftType: "ACTION", stars: 3, energy: 3, mass: 2, outcomeKind: "DAMAGE", base: 12, coefficient: 3, target: "SINGLE_ENEMY", rules: "Deal 4 damage three times. Apply 2 Fracture.", icons: [icon("system_stone"), icon("type_action")], art: libraryArt("stone", "advanced", "stone_fault_barrage"), effects: '[{"type":"DAMAGE_REPEAT","base":4,"hits":3,"compatible_system":"STONE","amplification_coefficient":3,"rounding":"FLOOR"},{"type":"APPLY_STATUS","status_id":"fracture","stacks":2}]' },
  { id: "stone_mirror_bastion", name: "MIRROR BASTION", set: "STONE 3★", system: "STONE", type: "ACTION", draftType: "ACTION", stars: 3, energy: 3, mass: 2, outcomeKind: "DAMAGE", base: 9, coefficient: 4, target: "SINGLE_ENEMY", rules: "Deal 9 damage. Gain Defend equal to damage dealt.", icons: [icon("system_stone"), icon("type_action")], art: libraryArt("stone", "advanced", "stone_mirror_bastion"), effects: '[{"type":"DAMAGE","base":9,"compatible_system":"STONE","amplification_coefficient":4,"rounding":"FLOOR","result_key":"damage_dealt"},{"type":"GAIN_DEFEND","value_source":{"type":"EFFECT_RESULT","effect_key":"damage_dealt","ratio":1},"rounding":"FLOOR"}]' },
  { id: "stone_mountain_stance", name: "MOUNTAIN STANCE", set: "STONE 3★", system: "STONE", type: "MAGIC", draftType: "BUFF", stars: 3, energy: 2, mass: 2, outcomeKind: "GAIN_DEFEND", base: 8, coefficient: 2, target: "SELF", rules: "Gain +8 Defend for 4 turns.", icons: [icon("system_stone"), icon("type_magic")], art: libraryArt("stone", "advanced", "stone_mountain_stance"), effects: '[{"type":"BUFF_STAT","stat":"DEFEND","base":8,"duration_turns":4,"compatible_system":"STONE","amplification_coefficient":2,"rounding":"FLOOR"}]' },
  { id: "stone_tectonic_pulse", name: "TECTONIC PULSE", set: "STONE 3★", system: "STONE", type: "MAGIC", draftType: "BUFF", stars: 3, energy: 3, mass: 2, outcomeKind: "GAIN_DEFEND", base: 7, coefficient: 3, target: "SELF", rules: "At turn start, gain 7 Defend for 3 turns.", icons: [icon("system_stone"), icon("type_magic")], art: libraryArt("stone", "advanced", "stone_tectonic_pulse"), effects: '[{"type":"APPLY_STATUS","status_id":"tectonic_pulse","tick_effect":{"type":"GAIN_DEFEND","base":7,"compatible_system":"STONE","amplification_coefficient":3,"rounding":"FLOOR"},"duration_turns":3}]' },
  { id: "stone_furnace_reserve", name: "FURNACE RESERVE", set: "STONE 3★", system: "STONE", type: "MAGIC", draftType: "BUFF", stars: 3, energy: 3, mass: 2, outcomeKind: "ENERGY", base: 2, coefficient: 3, target: "SELF", rules: "Gain 4 Defend. Gain +2 Energy at turn start for 2 turns.", icons: [icon("system_stone"), icon("type_magic")], art: libraryArt("stone", "advanced", "stone_furnace_reserve"), effects: '[{"type":"GAIN_DEFEND","base":4,"compatible_system":"STONE","amplification_coefficient":3,"rounding":"FLOOR"},{"type":"APPLY_STATUS","status_id":"furnace_reserve","tick_effect":{"type":"GAIN_ENERGY","base":2,"compatible_system":"STONE","amplification_coefficient":3,"rounding":"FLOOR"},"duration_turns":2}]' },
  { id: "stone_adamant_watch", name: "ADAMANT WATCH", set: "STONE 3★", system: "STONE", type: "PASSIVE", draftType: "PASSIVE", stars: 3, energy: 0, mass: 2, outcomeKind: "GAIN_DEFEND", base: 5, coefficient: 8, target: "SELF", rules: "While retained in hand, gain +5 Defend.", icons: [icon("system_stone"), icon("type_passive")], art: libraryArt("stone", "advanced", "stone_adamant_watch"), effects: '[{"type":"AURA","condition":{"card_in_hand":true},"stat":"DEFEND","base":5,"compatible_system":"STONE","amplification_coefficient":8,"rounding":"FLOOR"}]', retentionPolicy: "RETAIN_IN_HAND", occupiesDrawSlot: true },

  { id: "plant_starbloom_tempest", name: "STARBLOOM TEMPEST", set: "PLANT 4★", system: "PLANT", type: "ACTION", draftType: "ACTION", stars: 4, energy: 3, mass: 2, outcomeKind: "DAMAGE", base: 8, coefficient: 7, target: "ALL_ENEMIES", rules: "Deal 8 damage and apply 3 Poison to all enemies.", icons: [icon("system_plant"), icon("type_action")], art: libraryArt("plant", "rare", "plant_starbloom_tempest"), effects: '[{"type":"DAMAGE","base":8,"target":"ALL_ENEMIES","compatible_system":"PLANT","amplification_coefficient":7,"rounding":"FLOOR"},{"type":"APPLY_STATUS","target":"ALL_ENEMIES","status_id":"poison","stacks":3}]' },
  { id: "plant_phoenix_seed", name: "PHOENIX SEED", set: "PLANT 4★", system: "PLANT", type: "ACTION", draftType: "ACTION", stars: 4, energy: 3, mass: 2, outcomeKind: "HEAL_HULL", base: 14, coefficient: 9, target: "SELF", rules: "Heal 14 Hull. If Hull is below 25%, heal 6 more.", icons: [icon("system_plant"), icon("type_action")], art: libraryArt("plant", "rare", "plant_phoenix_seed"), effects: '[{"type":"HEAL_HULL","base":14,"compatible_system":"PLANT","amplification_coefficient":9,"rounding":"FLOOR"},{"type":"CONDITIONAL","condition":{"hull_below_percent":25},"effect":{"type":"HEAL_HULL","base":6}}]' },
  { id: "plant_worldroot_embrace", name: "WORLDROOT EMBRACE", set: "PLANT 4★", system: "PLANT", type: "MAGIC", draftType: "BUFF", stars: 4, energy: 3, mass: 2, outcomeKind: "GAIN_DEFEND", base: 7, coefficient: 8, target: "SELF", rules: "For 3 turns, gain 7 Defend and heal 7 Hull at turn start.", icons: [icon("system_plant"), icon("type_magic")], art: libraryArt("plant", "rare", "plant_worldroot_embrace"), effects: '[{"type":"APPLY_STATUS","status_id":"worldroot_embrace","duration_turns":3,"tick_effects":[{"type":"GAIN_DEFEND","base":7,"compatible_system":"PLANT","amplification_coefficient":8},{"type":"HEAL_HULL","base":7,"compatible_system":"PLANT","amplification_coefficient":8}]}]' },
  { id: "plant_genesis_cycle", name: "GENESIS CYCLE", set: "PLANT 4★", system: "PLANT", type: "MAGIC", draftType: "BUFF", stars: 4, energy: 3, mass: 2, outcomeKind: "HEAL_HULL", base: 5, coefficient: 8, target: "SELF", rules: "For 4 turns, heal 5 Hull and gain 1 Energy at turn start.", icons: [icon("system_plant"), icon("type_magic")], art: libraryArt("plant", "rare", "plant_genesis_cycle"), effects: '[{"type":"APPLY_STATUS","status_id":"genesis_cycle","duration_turns":4,"tick_effects":[{"type":"HEAL_HULL","base":5,"compatible_system":"PLANT","amplification_coefficient":8},{"type":"GAIN_ENERGY","base":1,"compatible_system":"PLANT","amplification_coefficient":8}]}]' },
  { id: "plant_solar_apotheosis", name: "SOLAR APOTHEOSIS", set: "PLANT 4★", system: "PLANT", type: "MAGIC", draftType: "BUFF", stars: 4, energy: 3, mass: 2, outcomeKind: "ENERGY", base: 3, coefficient: 6, target: "SELF", rules: "At next turn start, gain 3 Energy and draw 2 cards.", icons: [icon("system_plant"), icon("type_magic")], art: libraryArt("plant", "rare", "plant_solar_apotheosis"), effects: '[{"type":"DELAYED_EFFECT","delay_turns":1,"effects":[{"type":"GAIN_ENERGY","base":3,"compatible_system":"PLANT","amplification_coefficient":6},{"type":"DRAW_CARDS","count":2}]}]' },
  { id: "plant_thorn_crown_covenant", name: "THORN CROWN COVENANT", set: "PLANT 4★", system: "PLANT", type: "PASSIVE", draftType: "PASSIVE", stars: 4, energy: 0, mass: 3, outcomeKind: "DAMAGE", base: 3, coefficient: 10, target: "ALL_ENEMIES", rules: "While retained, your first heal each turn deals 3 damage to all enemies.", icons: [icon("system_plant"), icon("type_passive")], art: libraryArt("plant", "rare", "plant_thorn_crown_covenant"), effects: '[{"type":"TRIGGER","condition":{"card_in_hand":true},"event":"FIRST_HULL_HEAL_EACH_TURN","effect":{"type":"DAMAGE","base":3,"target":"ALL_ENEMIES","compatible_system":"PLANT","amplification_coefficient":10}}]', retentionPolicy: "RETAIN_IN_HAND", occupiesDrawSlot: true },
  { id: "plant_verdant_singularity", name: "VERDANT SINGULARITY", set: "PLANT 4★", system: "PLANT", type: "MAGIC", draftType: "SUMMON", stars: 4, energy: 4, mass: 3, outcomeKind: "SUMMON_HP", base: 18, coefficient: 8, target: "ALLY_SUMMON_SLOT", rules: "Summon a Verdant Core with 18 Hull.", icons: [icon("system_plant"), icon("type_magic")], art: libraryArt("plant", "rare", "plant_verdant_singularity"), effects: '[{"type":"SUMMON","summon_id":"verdant_core","base_hp":18,"compatible_system":"PLANT","amplification_coefficient":8,"rounding":"FLOOR"}]' },

  { id: "stone_extinction_array", name: "EXTINCTION ARRAY", set: "STONE 4★", system: "STONE", type: "ACTION", draftType: "ACTION", stars: 4, energy: 4, mass: 3, outcomeKind: "DAMAGE", base: 13, coefficient: 4, target: "ALL_ENEMIES", rules: "Deal 13 damage to all enemies.", icons: [icon("system_stone"), icon("type_action")], art: libraryArt("stone", "rare", "stone_extinction_array"), effects: '[{"type":"DAMAGE","base":13,"target":"ALL_ENEMIES","compatible_system":"STONE","amplification_coefficient":4,"rounding":"FLOOR"}]' },
  { id: "stone_planetary_anvil", name: "PLANETARY ANVIL", set: "STONE 4★", system: "STONE", type: "ACTION", draftType: "ACTION", stars: 4, energy: 4, mass: 3, outcomeKind: "DAMAGE", base: 17, coefficient: 3, target: "SINGLE_ENEMY", rules: "Deal 17 damage. Apply 3 Fracture.", icons: [icon("system_stone"), icon("type_action")], art: libraryArt("stone", "rare", "stone_planetary_anvil"), effects: '[{"type":"DAMAGE","base":17,"compatible_system":"STONE","amplification_coefficient":3,"rounding":"FLOOR"},{"type":"APPLY_STATUS","status_id":"fracture","stacks":3}]' },
  { id: "stone_citadel_convergence", name: "CITADEL CONVERGENCE", set: "STONE 4★", system: "STONE", type: "MAGIC", draftType: "BUFF", stars: 4, energy: 3, mass: 3, outcomeKind: "GAIN_DEFEND", base: 12, coefficient: 3, target: "SELF", rules: "Gain +12 Defend for 4 turns.", icons: [icon("system_stone"), icon("type_magic")], art: libraryArt("stone", "rare", "stone_citadel_convergence"), effects: '[{"type":"BUFF_STAT","stat":"DEFEND","base":12,"duration_turns":4,"compatible_system":"STONE","amplification_coefficient":3,"rounding":"FLOOR"}]' },
  { id: "stone_eventide_armor", name: "EVENTIDE ARMOR", set: "STONE 4★", system: "STONE", type: "MAGIC", draftType: "BUFF", stars: 4, energy: 3, mass: 3, outcomeKind: "GAIN_DEFEND", base: 10, coefficient: 3, target: "SELF", rules: "Gain 10 Defend. Reflect 50% of the next hit within 3 turns.", icons: [icon("system_stone"), icon("type_magic")], art: libraryArt("stone", "rare", "stone_eventide_armor"), effects: '[{"type":"GAIN_DEFEND","base":10,"compatible_system":"STONE","amplification_coefficient":3},{"type":"APPLY_STATUS","status_id":"eventide_reflect","ratio":0.5,"charges":1,"duration_turns":3}]' },
  { id: "stone_mantle_reactor", name: "MANTLE REACTOR", set: "STONE 4★", system: "STONE", type: "MAGIC", draftType: "BUFF", stars: 4, energy: 4, mass: 3, outcomeKind: "GAIN_DEFEND", base: 8, coefficient: 3, target: "SELF", rules: "For 3 turns, gain 8 Defend and 2 Energy at turn start.", icons: [icon("system_stone"), icon("type_magic")], art: libraryArt("stone", "rare", "stone_mantle_reactor"), effects: '[{"type":"APPLY_STATUS","status_id":"mantle_reactor","duration_turns":3,"tick_effects":[{"type":"GAIN_DEFEND","base":8,"compatible_system":"STONE","amplification_coefficient":3},{"type":"GAIN_ENERGY","base":2,"compatible_system":"STONE","amplification_coefficient":3}]}]' },
  { id: "stone_immutable_law", name: "IMMUTABLE LAW", set: "STONE 4★", system: "STONE", type: "PASSIVE", draftType: "PASSIVE", stars: 4, energy: 0, mass: 3, outcomeKind: "GAIN_DEFEND", base: 6, coefficient: 8, target: "SELF", rules: "While retained, gain +6 Defend and cap incoming hit damage at 10.", icons: [icon("system_stone"), icon("type_passive")], art: libraryArt("stone", "rare", "stone_immutable_law"), effects: '[{"type":"AURA","condition":{"card_in_hand":true},"stat":"DEFEND","base":6,"compatible_system":"STONE","amplification_coefficient":8},{"type":"DAMAGE_CAP","condition":{"card_in_hand":true},"max_per_hit":10}]', retentionPolicy: "RETAIN_IN_HAND", occupiesDrawSlot: true },
  { id: "stone_crystal_colossus", name: "CRYSTAL COLOSSUS", set: "STONE 4★", system: "STONE", type: "MAGIC", draftType: "SUMMON", stars: 4, energy: 4, mass: 3, outcomeKind: "SUMMON_HP", base: 24, coefficient: 5, target: "ALLY_SUMMON_SLOT", rules: "Summon a Crystal Colossus with 24 Hull.", icons: [icon("system_stone"), icon("type_magic")], art: libraryArt("stone", "rare", "stone_crystal_colossus"), effects: '[{"type":"SUMMON","summon_id":"crystal_colossus","base_hp":24,"compatible_system":"STONE","amplification_coefficient":5,"rounding":"FLOOR"}]' },
];

export function presetToDraft(card: CardPreset): CardDraft {
  return {
    ...EMPTY_CARD,
    id: card.id,
    name: card.name,
    faction: card.system,
    rarity: card.stars === 5 ? "LEGENDARY" : card.stars === 4 ? "RARE" : card.stars >= 2 ? "UNCOMMON" : "COMMON",
    type: card.draftType,
    stars: card.stars,
    energy_cost: card.energy,
    mass: card.mass,
    outcome_kind: card.outcomeKind,
    base_value: card.base,
    amplification_coefficient: card.coefficient,
    target: card.target,
    rules_text: card.rules,
    effects_json: card.effects,
    art_name: card.art.split("/").pop() ?? `${card.id}_art.png`,
    art_data_url: card.art,
    tags: [card.system, card.draftType, card.set.replace(" 1★", "_ONE_STAR").replace(" 2★", "_TWO_STAR").replace(" 3★", "_THREE_STAR").replace(" 4★", "_FOUR_STAR")],
    stamps: card.system === "STONE" ? ["faction_stone", card.type === "PASSIVE" ? "type_passive" : card.type === "MAGIC" ? "type_magic" : "type_action"] : card.system === "PLANT" ? ["faction_plant", card.type === "PASSIVE" ? "type_passive" : card.type === "MAGIC" ? "type_magic" : "type_action"] : ["faction_hybrid", "type_passive"],
    retention_policy: card.retentionPolicy ?? "DISCARD_END_TURN",
    occupies_draw_slot: card.occupiesDrawSlot ?? false,
  };
}
